function getCollectDate(){
    let obj = [
        {
            "model":{
                "set1":"left",
                "set2":"big"
             },
             "ahref":"",
             "bigsrc":"panoply-pc-1.jpg",
             "ulbox":[
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 }
             ]
        },
        {
            "model":{
                "set1":"right",
                "set2":"little"
             },
             "ahref":"",
             "bigsrc":"panoply-pc-2.jpg",
             "ulbox":[
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 }
             ]
        },
        {
            "model":{
                "set1":"left",
                "set2":"little"
             },
             "ahref":"",
             "bigsrc":"panoply-pc-3.jpg",
             "ulbox":[
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 }
             ]
        },
        {
            "model":{
                "set1":"left",
                "set2":"little"
             },
             "ahref":"",
             "bigsrc":"panoply-pc-1.jpg",
             "ulbox":[
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 },
                 {
                    "price":149.90,
                    "url":"Discovery+Soft+Archery+Target+Boss.jpg",
                    "brand":"GEOLOGIC",
                    "desc":"射箭运动软件靶<br>DISCOVERY",
                    "rate":"4.4(10条评价)"
                 }
             ]
        }
    ]
    return obj;
}