function getNavDate(){
    let navdate = [
        [
                {
                    "navtitle":"所有运动",
                    "navhref":"1",
                    "navchildclass":"liclass1",
                    "childmodel":"false",
                    "child":[
                        {   
                            "href":"",
                            "url":"menuThumbnail_fitness.png",
                            "title":"健身"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_running.png",
                            "title":"跑步"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_road_cycling.png",
                            "title":"自行车"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_hiking.png",
                            "title":"一日徒步"
                        },
                        {
                            "href":"",
                            "url":"MenuThumbnail_Trekking.png",
                            "title":"多日徒步"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_camping.png",
                            "title":"户外露营"
                        },
                        {
                            "href":"",
                            "url":"MenuThumbnail_Pilates.png",
                            "title":"基础健身/普拉提"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_yoga.png",
                            "title":"瑜伽"
                        },
                        {
                            "href":"",
                            "url":"MenuThumbnail_fitness_child.png",
                            "title":"儿童体能"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_football.png",
                            "title":"足球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_basketball.png",
                            "title":"篮球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_walking.png",
                            "title":"健走"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_badminton.png",
                            "title":"羽毛球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_tennis.png",
                            "title":"网球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_table_tennis.png",
                            "title":"乒乓球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_scooter.png",
                            "title":"滑板车"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_sport_inline.png",
                            "title":"轮滑"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_skateboard.png",
                            "title":"滑板"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_swiming.png",
                            "title":"游泳"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_diving.png",
                            "title":"潜水"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_surf.png",
                            "title":"冲浪"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_golf.png",
                            "title":"高尔夫"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_sailing.png",
                            "title":"帆船"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_skiing.png",
                            "title":"滑雪"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_exploring.png",
                            "title":"荒野探险"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_horse_riding.png",
                            "title":"马术"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_fishing.png",
                            "title":"钓鱼"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_climbing.png",
                            "title":"攀岩/高山攀登"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_dance.png",
                            "title":"舞蹈"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_combat_sport.png",
                            "title":"拳击"
                        },
                        {
                            "href":"",
                            "url":"MenuThumbnail_triathlon.png",
                            "title":"铁人三项"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_darts.png",
                            "title":"飞镖"
                        },
                        {
                            "href":"",
                            "url":"achery+icon.png",
                            "title":"射箭"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_ice_skating.png",
                            "title":"冰上运动"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_canoeing.png",
                            "title":"皮划艇/SUP桨板"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_baseball.png",
                            "title":"棒球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_rugby.png",
                            "title":"橄榄球"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_trail_running.png",
                            "title":"越野跑"
                        },
                        {
                            "href":"",
                            "url":"menuThumbnail_squash.png",
                            "title":"壁球"
                        }
                    ]
                },
                {
                    "navtitle":"运动服饰",
                    "navhref":"2",
                    "navchildclass":"liclass2",
                    "childmodel":"true",
                    "child":[
                        { 
                            "title":"户外运动",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"一日徒步服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"多日徒步服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"滑雪服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"攀岩/高山攀登服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"室内健身",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"健身服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"舞蹈服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"瑜伽服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"普拉提服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"武术服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"儿童体能服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"水上运动",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"游泳服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"冲浪服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"航海服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"潜水服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"皮划艇/SUP桨板服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"水中有氧服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"跑步健走",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"跑步服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"健走服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"团体运动",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"足球服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"篮球服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"排球服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"橄榄球服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"棒球服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"球拍对抗",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"羽毛球服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"网球服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"骑行滑行",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"骑行服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"目标运动",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"高尔夫服饰"
                                        }
                                ]
                        },
                        { 
                            "title":"接触自然",
                            "child":[
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"钓鱼服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"马术服饰"
                                        },
                                        {
                                            "href":"",
                                            "url":"",
                                            "title":"荒野探险服饰"
                                        }
                                ]
                        }
                        
                    ]
                },
                {
                "navtitle":"运动鞋袜",
                "navhref":"3",
                "navchildclass":"liclass2",
                "childmodel":"true",
                "child":[
                    { 
                        "title":"户外运动",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"一日徒步鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"多日徒步鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"攀岩/高山攀登鞋"
                                    }
                            ]
                    },
                    { 
                        "title":"室内健身",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"健身鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"儿童体能鞋袜"
                                    }
                            ]
                    },
                    { 
                        "title":"水上运动",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"游泳拖鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"冲浪鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"航海鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"潜水鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"皮划艇/SUP桨板鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"水中有氧服鞋"
                                    }
                            ]
                    },
                    { 
                        "title":"跑步健走",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"跑步鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"健走鞋袜"
                                    }
                            ]
                    },
                    { 
                        "title":"团体运动",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"足球鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"篮球鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"排球鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"橄榄球鞋"
                                    }
                            ]
                    },
                    { 
                        "title":"球拍对抗",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"羽毛球鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"网球鞋袜"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"乒乓球鞋袜"
                                    }
                            ]
                    },
                    { 
                        "title":"骑行滑行",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"骑行鞋袜"
                                    }
                            ]
                    },
                    { 
                        "title":"目标运动",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"高尔夫鞋袜"
                                    }
                            ]
                    },
                    { 
                        "title":"接触自然",
                        "child":[
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"马术鞋"
                                    },
                                    {
                                        "href":"",
                                        "url":"",
                                        "title":"荒野探险鞋"
                                    }
                            ]
                    }
                    
                ]
            },
            {
            "navtitle":"运动装备",
            "navhref":"3",
            "navchildclass":"liclass2",
            "childmodel":"true",
            "child":[
                { 
                    "title":"户外运动",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"一日徒步装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"多日徒步装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"露营装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"滑雪装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"攀岩/高山攀登装备"
                                }
                        ]
                },
                { 
                    "title":"室内健身",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"有氧健身装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"儿童体能装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"瑜伽/普拉提装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"拳击装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"循环训练装备"
                                }
                        ]
                },
                { 
                    "title":"水上运动",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"游泳装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"冲浪装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"航海装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"潜水装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"皮划艇/SUP桨板装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"水中有氧装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"风筝装备"
                                }
                        ]
                },
                { 
                    "title":"跑步健走",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"跑步装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"健走装备"
                                }
                        ]
                },
                { 
                    "title":"团体运动",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"足球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"篮球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"排球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"橄榄球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"棒球装备"
                                }
                        ]
                },
                { 
                    "title":"球拍对抗",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"羽毛球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"网球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"乒乓球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"壁球装备"
                                }
                        ]
                },
                { 
                    "title":"骑行滑行",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"骑行装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"滑板车装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"轮滑装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"滑板装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"滑冰装备"
                                }
                        ]
                },
                { 
                    "title":"目标运动",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"高尔夫装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"弓箭装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"台球装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"飞镖装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"法式地滚球/芬兰撞柱装备"
                                }
                        ]
                },
                { 
                    "title":"接触自然",
                    "child":[
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"钓鱼装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"荒野探险装备"
                                },
                                {
                                    "href":"",
                                    "url":"",
                                    "title":"马术装备"
                                }
                        ]
                }
                
            ]
         }
        ],
        [
            {
                "navtitle":"特惠专区",
                "navhref":"5",
                "navchildclass":""
            },
            {
                "navtitle":"保养维修",
                "navhref":"6",
                "navchildclass":""
            },
            {
                "navtitle":"个性定制",
                "navhref":"7",
                "navchildclass":""
            }
        ]
          
    ];
    return navdate;
}